version: 0.2

run-as: art

env:
  variables:
    HOME: /home/art
    SERVICE_NAME: "hello"
    SLACK_CHANNEL: ""
    USERDATA_PATH: scripts/userdata.sh
    REGION: "ap-northeast-2"
    STACK: "artp"
    BASE_AMI_ID: ""
    RELEASE_NOTE: "Hello DevOps"
  parameter-store:
    SLACK_TOKEN: "/CodeBuild/SLACK_TOKEN"
    SLACK_WEBHOOK_URL: "/CodeBuild/SLACK_WEBHOOK_URL"

phases:
  install:
    commands:
      - curl -Lo goployer https://goployer.s3.ap-northeast-2.amazonaws.com/experimental/latest/goployer-linux-amd64
      - sudo install goployer /usr/local/bin/
  build:
    commands:
      - echo "Start Deployment"
      - /usr/local/bin/goployer deploy ${ASSUME_ROLE} --manifest=manifests/${SERVICE_NAME}.yaml --stack=${STACK} --region=${REGION} --log-level=debug --release-notes "${RELEASE_NOTES}" --polling-interval=20s --slack-off
#  post_build:
#    commands:
